development:
  secret_key_base: db905d3a433c3f67add3bf13f8fc899bc14375c90b1a0ac3dba9803dc85bd8d08530477882ea74a28f9088d31f11180a7dfe2551c26b608fff5c9a45eedf5b6e
  facebook_app_id: 485910831617891
  facebook_app_secret: <%= ENV["KITTEN_HUB_APP_SECRET"] %>

test:
  secret_key_base: ac6c953f8d6269caa3b56be8da83d596ad95e21448a892110c9e11951f58fd1724acbe7cf1b1bb3e0e050c1fb47610bee1992d73e3146d3b201626e8bb47a698
  facebook_app_id: 485910831617891
  facebook_app_secret: <%= ENV["KITTEN_HUB_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 485910831617891
  facebook_app_secret: <%= ENV["KITTEN_HUB_APP_SECRET"] %>
